services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: switchonyourcode
      POSTGRES_USER: switchonyourcode
      POSTGRES_PASSWORD: switchonyourcode
    ports:
      - "5432:5432"
    volumes:
      - switchonyourcode-postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U switchonyourcode -d switchonyourcode"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  switchonyourcode-postgres:
